:version: 1.0.0

= Bower Installer Gradle Plugin

The Gradle plugin uses https://github.com/blittle/bower-installer[bower-installer] to manage client-side dependencies alongside the other
dependencies in *build.gradle.* 

NOTE: You need to have the https://github.com/srs/gradle-node-plugin[Node Gradle plugin] applied in order to use this.

== Getting Started

[source,gradle,subs='attributes']
----
buildscript {
    repositories {
        mavenLocal()
    }
    dependencies {
        classpath "com.craigburke.gradle:bower-installer:{version}"
    }
}

plugins {
    id 'com.moowork.node' version '0.10'
}

apply plugin: 'bower-installer'
----

== Tasks

The plugin adds the following tasks to your build:

|===

| *Task* | *Description* 

| bowerInstall | Installs all the bower dependencies you have set in your build.gradle 

| bowerRefresh | Refreshes bower dependencies (if you add or modify your bower configuration)

| bowerClean | Removes bower dependencies and clears Bower's cache

|===

== Configuration

You can use the same properties you'd set in your http://bower.io/docs/creating-packages/#bowerjson[bower.json file] directly in *build.gradle*

[source,gradle,subs='attributes']
----
buildscript {
    repositories {
        mavenLocal()
    }
    dependencies {
        classpath "com.craigburke.gradle:bower-installer:{version}"
    }
}

plugins {
    id 'com.moowork.node' version '0.10'
}

apply plugin: 'bower-installer'

bower { // <1>
    name = 'myApp'
    version = '1.0'
    authors = 'Craig Burke <craig@craigburke.com>'
    license = 'MIT'
    dependencies = [ // <2>
            'angular'                   : '1.3.x',
            'angular-animate'           : '1.3.x',
            'ui-router'                 : '0.2.x',
            'bootstrap'                 : '3.3.x',
            'animate.css'               : '3.3.x'
    ]
    install = [ // <3>
            sources: [bootstrap: ['bower_components/bootstrap/dist/**']],
            ignore : ['jquery']
    ]
}
----
<1> Use all the same properties you would see in a http://bower.io/docs/creating-packages/#bowerjson[bower.json file] 
<2> Map of bower dependencies to download.
<3> Use https://github.com/blittle/bower-installer[bower-installer] configuration settings.

=== Optional properties
In addition to the standard http://bower.io/docs/creating-packages/#bowerjson[bower.json properties], you can also include a *debug*, *installPath* or an *additional* property.
 
[source,gradle,subs='attributes']
----
bower {
	debug = true // <1>
	installPath = 'src/assets' // <2>
	
	additional = [ // <3>
		'private': 'true'
	]
}

----
<1> *debug* preserves the bower.json file and bower_components folder after the bowerInstall task is run to help with troubleshooting
<2> *installPath* is the path that the bower dependencies are installed to
<3> *additional* is a map that allows additional properties to be added to the generated bower.json file

== Contributions

Thank you to the following people who have made major contributions in terms of both feedback and code:

* https://github.com/VoltiSubito[Jason Schindler]
