:version: 1.3.0

= Bower Installer Gradle Plugin

The Gradle plugin uses https://github.com/blittle/bower-installer[bower-installer] to manage client-side dependencies alongside the other
dependencies in *build.gradle.* 

NOTE: You need to have the https://github.com/srs/gradle-node-plugin[Node Gradle plugin] applied in order to use this.

== Getting Started

[source,gradle,subs='attributes']
----
plugins {
    id 'com.moowork.node' version '0.10'
    id 'com.craigburke.bower-installer' version '{version}'
}
----

== Tasks

The plugin adds the following tasks to your build:

|===

| *Task* | *Description* 

| bowerInstall | Installs all the bower dependencies you have set in your build.gradle 

| bowerRefresh | Refreshes bower dependencies (if you add or modify your bower configuration)

| bowerClean | Removes bower dependencies and clears Bower's cache

|===

== Configuration

You can use the same properties you'd set in your http://bower.io/docs/creating-packages/#bowerjson[bower.json file] directly in *build.gradle*

[source,gradle,subs='attributes']
----
plugins {
    id 'com.moowork.node' version '0.10'
    id 'com.craigburke.bower-installer' version '{version}'
}

bower {
    installBase = 'src/assets/bower' // <1>

    dependencies = [ // <2>
        'angular'                   : '1.3.x',
        'angular-animate'           : '1.3.x',
        'ui-router'                 : '0.2.x',
        'bootstrap'                 : '3.3.x',
        'animate.css'               : '3.3.x'
    ]
    
    sources = [ // <3>
        'bootstrap': ['dist/**']
    ]
    
    ignore = ['jquery'] // <4>
}
----
<1> *installBase* is the path that the bower dependencies are installed to.
<2> *dependencies* is a list of dependencies that should be installed by bower.
<3> *sources* helps you optionally limit what files get installed for each dependency.
<4> *ignore* allows you to set transitive dependencies that shouldn't be installed.

NOTE: if installBase is not set, it defaults to `src/assets/bower` or `grails-app/assets/bower` if the Grails plugin is applied.

=== Advanced properties

[source,gradle]
----
bower {
    mapping = [ // <1>
        js : ['js'],
        css: ['css'],
        less: ['less'],
        sass: ['sass', 'scss'],
        fonts: ['ttf', 'woff', 'woff2', 'eot', 'otf', 'svg']
    ]

    additional = [ // <2>
        name: 'gradle-bower-installer'
    ]
    
}
----
<1> *mapping* helps you control what folder 
<2> *additional* allow you to set optional properties in the generated http://bower.io/docs/creating-packages/#bowerjson[bower.json file].

NOTE: An example of how the mapping works with the setting above. For the twitter bootstrap all file with font extensions will be installed into `bootstrap/fonts`, all javascript to `bootstrap/js` etc.

=== Troubleshooting

If you set the bowerDebug property when you run *bowerInstall* then both the `bower.json` file and the `bower_components` folder will remain to help troubleshoot.

[source,bash]
----
./gradlew bowerInstall -PbowerDebug=true
----

== Contributions

Thank you to the following people who have made major contributions in terms of both feedback and code:

* https://github.com/VoltiSubito[Jason Schindler]
