:version: 1.0.0

= Bower Installer Gradle Plugin

The Gradle plugin uses https://github.com/blittle/bower-installer[bower-installer] to manage client-side dependencies alongside the other
dependencies in *build.gradle.* 

NOTE: You need to have the https://github.com/srs/gradle-node-plugin[Node Gradle plugin] applied in order to use this.

== Getting Started

[source,gradle,subs='attributes']
----
buildscript {
    repositories {
        mavenLocal()
    }
    dependencies {
        classpath "com.craigburke.gradle:bower-installer:{version}"
    }
}

plugins {
    id 'com.moowork.node' version '0.10'
}

apply plugin: 'bower-installer'
----

== Tasks

The plugin adds the following tasks to your build:

|===

| *Task* | *Description* 

| bowerInstall | Installs all the bower dependencies you have set in your build.gradle 

| bowerRefresh | Refreshes bower dependencies (if you add or modify your bower configuration)

| bowerClean | Removes bower dependencies and clears Bower's cache

|===

== Configuration

You can use the same properties you'd set in your http://bower.io/docs/creating-packages/#bowerjson[bower.json file] directly in *build.gradle*

[source,gradle,subs='attributes']
----
buildscript {
    repositories {
        mavenLocal()
    }
    dependencies {
        classpath "com.craigburke.gradle:bower-installer:{version}"
    }
}

plugins {
    id 'com.moowork.node' version '0.10'
}

apply plugin: 'bower-installer'

bower {
    dependencies = [ // <1>
            'angular'                   : '1.3.x',
            'angular-animate'           : '1.3.x',
            'ui-router'                 : '0.2.x',
            'bootstrap'                 : '3.3.x',
            'animate.css'               : '3.3.x'
    ]
    install = [ // <2>
            path: 'src/assets/bower', // <3>
            sources: [bootstrap: ['bower_components/bootstrap/dist/**']],
            ignore : ['jquery']
    ]
}
----
<1> List of bower dependencies to install.
<2> Set https://github.com/blittle/bower-installer[bower-installer] configuration settings in the install map.
<3> The *path* is the path that the bower dependencies are installed to.

NOTE: if install.path is not set, it defaults to `src/assets/bower` or `grails-app/assets/bower` if the Grails plugin is applied.

=== Optional properties

In addition to the properties listed above, you can also include a *debug* or an *additional* properties.
 
[source,gradle,subs='attributes']
----
bower {
    debug = true // <1>
    additional = [ // <2>
        name: 'myApp'
    ]
}
----
<1> *debug* preserves the bower.json file and bower_components folder after the bowerInstall task is run to help with troubleshooting
<2> *additional* is a map that allows additional properties to be added to the generated http://bower.io/docs/creating-packages/#bowerjson[bower.json file]

== Contributions

Thank you to the following people who have made major contributions in terms of both feedback and code:

* https://github.com/VoltiSubito[Jason Schindler]
