:version: 2.0.0

= Bower Installer Gradle Plugin

The Gradle plugin uses https://github.com/blittle/bower-installer[bower-installer] to manage client-side dependencies alongside the other
dependencies in *build.gradle.* 

NOTE: You need to have the https://github.com/srs/gradle-node-plugin[Node Gradle plugin] applied in order to use this.

== Getting Started

[source,gradle,subs='attributes']
----
plugins {
    id 'com.moowork.node' version '0.10'
    id 'com.craigburke.bower-installer' version '{version}'
}
----

== Tasks

The plugin adds the following tasks to your build:

|===

| *Task* | *Description* 

| bowerInstall | Installs all the bower dependencies you have set in your build.gradle 

| bowerRefresh | Refreshes bower dependencies (if you add or modify your bower configuration)

| bowerClean | Removes bower dependencies and clears Bower's cache

|===

== Configuration

You can specify dependencies as well as control where files are installed to with the provided dependency DSL.

[source,gradle,subs='attributes']
----
plugins {
    id 'com.moowork.node' version '0.10'
    id 'com.craigburke.bower-installer' version '{version}'
}

bower {
    installBase = 'src/assets/bower' // <1>

    dependencies {
        
        'angular:1.3.x' {
            source 'angular.js' // <2>
        }
         
        'angular-animate:1.3.x' {
            source 'angular-animate.js' >> '/angular/modules' // <3>
        }
        
        'ui-router:0.2.x'() // <4>
        
        'bootstrap:3.3.x' {
            source 'dist/css/*.min.css' >> 'styles'
            source 'dist/fonts/**' >> 'fonts'

            excludes 'jquery' // <5>
        }

    }
}
----
<1> *installBase* is the base path that the bower dependencies are installed to
<2> This copies the *angular.js* file to the default location (`src/assets/bower/angular/angular.js`)
<3> An absolute path is used here so `angular-animate.js` will be copied to `src/assets/bower/angular/modules/angular-animate.js`
<4> When no sources are specified the default behavior of bower-installer determines which files are included
<5> Exclude the transitive dependency jquery


NOTE: if installBase is not set, it defaults to `src/assets/bower`.

=== Advanced properties

[source,gradle]
----
bower {
    additional = [ // <1>
        name: 'gradle-bower-installer'
    ]
}
----
<1> *additional* allow you to set optional properties in the generated http://bower.io/docs/creating-packages/#bowerjson[bower.json file].

=== Troubleshooting

If you set the bowerDebug property when you run *bowerInstall* then both the `bower.json` file and the `bower_components` folder will remain to help troubleshoot.

[source,bash]
----
./gradlew bowerInstall -PbowerDebug=true
----

== Contributions

Thank you to the following people who have made major contributions in terms of both feedback and code:

* https://github.com/VoltiSubito[Jason Schindler]
