:version: 1.1.1

= Bower Installer Gradle Plugin

The Gradle plugin uses https://github.com/blittle/bower-installer[bower-installer] to manage client-side dependencies alongside the other
dependencies in *build.gradle.* 

NOTE: You need to have the https://github.com/srs/gradle-node-plugin[Node Gradle plugin] applied in order to use this.

== Getting Started

[source,gradle,subs='attributes']
----
plugins {
    id 'com.moowork.node' version '0.10'
    id 'com.craigburke.bower-installer' version '{version}'
}
----

== Tasks

The plugin adds the following tasks to your build:

|===

| *Task* | *Description* 

| bowerInstall | Installs all the bower dependencies you have set in your build.gradle 

| bowerRefresh | Refreshes bower dependencies (if you add or modify your bower configuration)

| bowerClean | Removes bower dependencies and clears Bower's cache

|===

== Configuration

You can use the same properties you'd set in your http://bower.io/docs/creating-packages/#bowerjson[bower.json file] directly in *build.gradle*

[source,gradle,subs='attributes']
----
plugins {
    id 'com.moowork.node' version '0.10'
    id 'com.craigburke.bower-installer' version '{version}'
}

bower {
    dependencies = [ // <1>
            'angular'                   : '1.3.x',
            'angular-animate'           : '1.3.x',
            'ui-router'                 : '0.2.x',
            'bootstrap'                 : '3.3.x',
            'animate.css'               : '3.3.x'
    ]
    install = [ // <2>
            base: 'src/assets/bower', // <3>
            sources: [bootstrap: ['bower_components/bootstrap/dist/**']],
            ignore : ['jquery']
    ]
}
----
<1> List of bower dependencies to install.
<2> Set https://github.com/blittle/bower-installer[bower-installer] configuration settings in the install map.
<3> The *base* is the path that the bower dependencies are installed to.

NOTE: if install.base is not set, it defaults to `src/assets/bower` or `grails-app/assets/bower` if the Grails plugin is applied.

=== Additional properties

You can include any other properties you'd normally set in a http://bower.io/docs/creating-packages/#bowerjson[bower.json file] by setting the value in the
*additional* map.
 
[source,gradle,subs='attributes']
----
bower {
    additional = [
        name: 'myApp'
    ]
}
----

=== Troubleshooting

If you set the bowerDebug property when you run *bowerInstall* then both the `bower.json` file and the `bower_components` folder will remain to help troubleshoot.

[source,bash]
----
./gradlew bowerInstall -PbowerDebug=true
----

== Contributions

Thank you to the following people who have made major contributions in terms of both feedback and code:

* https://github.com/VoltiSubito[Jason Schindler]
